name: Build mntool

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        lazarus-versions: [2.0.12]
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/instantfpc
          ~/.lazarus
          /usr/share/lazarus/${{ matrix.lazarus-versions }}
          /usr/bin/lazbuild
        key: ${{ runner.os }}-laz-${{ matrix.lazarus-versions }}-v1
        restore-keys: |
          ${{ runner.os }}-laz-
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.9
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - uses: actions/checkout@v2
    - name: Unzip packages
      run: unzip -q Packages/\*.zip -d Packages
    - name: Install packages
      run: |
        lazbuild -qqq Packages/Indy10/indylaz.lpk
    - name: Build the Main Application
      run: lazbuild -B --bm="Release" "mntool.lpi"
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.operating-system }}
        path: |
          mntool
          mntool.exe

  package-release:
    if: contains(github.ref, '/tags/')
    name: Package and Upload
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        name: Download Artifacts
      - name: List everything
        run: |
          ls -al
          ls -al windows-latest
          ls -al ubuntu-latest
      - name: Package Windows
        run: |
          cp windows-latest/mntool.exe .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          zip mntool-${tag}-x86_64-win64.zip mntool.exe
      - name: Package Linux
        run: |
          cp ubuntu-latest/mntool .
          tag=${{ github.event.ref }}
          tag=${tag#"refs/tags/"}
          tar -zcvf mntool-${tag}-x86_64-linux.tgz mntool
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mntool-*.zip
            mntool-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
